services:
  db:
    image: postgres:16
    container_name: pft_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pft_pgdata:/var/lib/postgresql/data

volumes:
  pft_pgdata:
